config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/pages/about.html.erb
<h1>Sample App</h1>
<p>This is the about page for the Ruby on Rails tutorial sample app.</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>This is the contact page for the RoR Tutorial Sample app</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on Ruby on Rails Tutorial at the 
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>
  To get help on this sample app, see the
  <a href"http://railstutorial.org/book">Rails Tutorial book</a>
</p>

app/views/pages/home.html.erb
<% if signed_in? %>

  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">What's up?</h1>
        <%= render 'shared/micropost_form' %>
        <%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
        <%= render 'shared/stats' %>
      </td>
    </tr>
  </table>

<% else %>

  <h1>Sample App</h1>
  <p>This is the home page for the <a href="http://railstutorial.org">Ruby on Rails Tutorial</a> sample app.</p>

  <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

<% end %>